WIP - JI:759431 P2022-463 Presentation title and description
intive/patronage22-web-wroclaw pull request #31
Opened 2022-02-12 21:53 UTC by Adys23

Basic form for title and description updates. Error handling still not functional.

2022-02-13 14:20 UTC, krysia1 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +import React, { useState } from "react";
I don't think we need to import React

2022-02-13 14:20 UTC, krysia1 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +  const [formDisabled, setFormDisabled] = useState<boolean>(true);
I think name `isFormDisabled` would look a tad better 💃

2022-02-13 14:39 UTC, pawelwojdas commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +    console.log(data);
The same as in my case - https://github.com/intive/patronage22-web-wroclaw/blob/develop/README.md#naming-conventions

2022-02-13 14:46 UTC, pawelwojdas commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +    setFormDisabled(!formDisabled);
I think that we should use prevState and then exclamation mark to define a value.

2022-02-13 16:14 UTC, krysia1 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +              placeholder='Description'
I think there should be translations for `defaultValue` and `placeholder`

2022-02-13 20:29 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +              placeholder='Description'
True, I did not manage to add them yesterday. They are added now.

2022-02-13 20:33 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +    console.log(data);
Corrected :)

2022-02-13 20:35 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +  const [formDisabled, setFormDisabled] = useState<boolean>(true);
I cannot agree more with that :) Corrected.

2022-02-13 20:36 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +import React, { useState } from "react";
Yes, thanks for spotting.

2022-02-14 11:58 UTC, krysia1 commented
LGTM, waiting for leader's approval 😄

2022-02-15 08:10 UTC, FabianHoffmannIntive requested changes
Please resolve comments

2022-02-15 13:03 UTC, kacperChlon commented on package.json
>    },
+ https://www.npmjs.com/package/@types/yup

2022-02-15 13:05 UTC, kacperChlon commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +    <Styled.Form component='form'>
https://mui.com/api/form-control/

2022-02-18 12:26 UTC, pawelwojdas commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +    const currentValues = getValues();
Can we destructure `title` and `description`?

2022-02-18 12:27 UTC, pawelwojdas commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +  const [isFormDisabled, setIsFormDisabled] = useState<boolean>(true);
If we're inside form component shouldn't we just name it as `isDisabled`?

2022-02-18 12:29 UTC, pawelwojdas commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +  const handleFormSubmit = (): void => {
Isn't just `handleSubmit` sufficient?

2022-02-18 12:33 UTC, pawelwojdas commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +    resolver: yupResolver(schema),
If we use `formState.errors` in few places can we just destructure and assign to constant. Then we'll be able to use only `errors`

2022-02-18 12:38 UTC, pawelwojdas commented on libs/features/feedback/src/components/title-and-description-form/styled.tsx
> +  display: "flex",
Aren't these `BoxProps` set autimatically? Do we need to set them?

2022-02-18 12:39 UTC, pawelwojdas commented on libs/features/feedback/src/components/title-and-description-form/styled.tsx
> +export const Form = styled(Box)<BoxProps>(({ theme }) => ({
Aren't these `BoxProps` set autimatically? Do we need to set them?

2022-02-18 12:40 UTC, pawelwojdas commented on libs/features/feedback/src/components/title-and-description-form/styled.tsx
> +    border: "1px solid #d32f2f"
We use theme to set colors

2022-02-18 12:40 UTC, pawelwojdas commented on libs/features/feedback/src/components/title-and-description-form/styled.tsx
> +  color: "#d32f2f"
https://github.com/intive/patronage22-web-wroclaw/pull/31/files#r809962764

2022-02-23 10:31 UTC, kacperChlon commented on libs/shared/src/types/form.ts
> +export enum FieldTypes {
Following convention in our project please rename it to:

```
FieldType {
   TextField = 'text-field'
}
```

2022-02-23 10:34 UTC, kacperChlon commented on libs/translations/src/feedback/en.json
> +  "save": "Save",
save, submit are more related with common namespace than feedback ;)

2022-02-23 14:45 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +                Submit
Done

2022-02-23 14:48 UTC, Adys23 commented on package.json
>    },
Added

2022-02-23 14:55 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +  const [isFormDisabled, setIsFormDisabled] = useState<boolean>(true);
We could, but I think the point here was to distinguish between form and field being disabled. Nevertheless, I am not using it in the latest version.

2022-02-23 14:56 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +  const handleFormSubmit = (): void => {
handleSubmit was already reserved for useForm hook method.

2022-02-23 14:57 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +    resolver: yupResolver(schema),
True. I have used that approach in the newest version.

2022-02-23 14:58 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/styled.tsx
> +    border: "1px solid #d32f2f"
Good point. I got rid of that.

2022-02-23 14:59 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/styled.tsx
> +  color: "#d32f2f"
Same here.

2022-02-24 11:22 UTC, kacperChlon commented on libs/features/feedback/src/components/basic-presentation-info/index.tsx
> +      defaultValue: t(" "),
for such case there is no reasonn for translation ,omitting defaultValue will be fine

2022-02-24 11:24 UTC, kacperChlon commented on libs/features/feedback/src/components/basic-presentation-info/index.tsx
> +      hasEditIcon: true
let's change the logic and this boolean to: hideEditIcon, in the componennt it will be false by default, hence we won't need to pass it everytime and still will have same behaviour

2022-02-24 11:25 UTC, kacperChlon commented on libs/features/feedback/src/components/basic-presentation-info/index.tsx
> +    {
please order properties in the same manner, it will be easier to read

2022-02-24 11:25 UTC, kacperChlon commented on libs/features/feedback/src/components/basic-presentation-info/index.tsx
> +      hasSubmitButton={false}
showSubmitButton?

2022-02-24 11:27 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +
please destructure here all mandatory properties that are required from field object

2022-02-24 11:28 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +        error={errors[`${name}`]}
move it to const hasError

2022-02-24 11:29 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +        {...(errors[`${name}`] && { helperText: errors[`${name}`].message })}
helperText={renderHelperText()}

const renderHelperText = () => {
// returns proper component if there is an error (like red color etc...) and proper component if user passed helpLabel in props.
}

2022-02-24 11:31 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +        {...(!field.value && { defaultValue })}
if field has got a value it shouldn't show defaultValue unnder the hood

2022-02-24 11:33 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +        {...(isMultiline && { rows: rows || 4 })}
please avoid doing {...()} try to move this to separate function and handle it like: rows={setFieldRows} <- if you're going to do that then move whole componnent to the separate file :)

2022-02-24 11:34 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +      {hasEditIcon && <Edit />}
like this or <Edit hidden={...} />

2022-02-24 11:40 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +  const { ...methods } = useForm<FieldValues>({
what's the difference between const {...methods} = vs. const methods = ?

2022-02-24 11:41 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +      <form className={className}>
do we need to use className here or can we just add Box wrapper below form element?

2022-02-24 11:41 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +        {formTitle && <Typography>{formTitle}</Typography>}
formTitle => title

2022-02-24 11:42 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +          <BaseButton type={ButtonType.Basic} onClick={methods.handleSubmit(onSubmit, onError)} variant='contained'>
let's make handleSubmit function and encapsulate it there

2022-02-24 11:43 UTC, kacperChlon commented on libs/shared/tsconfig.json
> +    "noPropertyAccessFromIndexSignature": false,
tsconnfigs innhert/extend base tsconfig file, so you can add thhis property there and should be fine for all

2022-02-24 11:44 UTC, kacperChlon commented on libs/ui/src/stories/basic-presentation-info/basic-presentation-info.stories.tsx
> +export const BasicPresentationInfoStory: React.FC = () => <BasicPresentationInfo />;
Let's change it to form and make storybook of a Form component to which we will be adding more fields, not this one :)

2022-02-25 08:33 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/index.tsx
> +    <Styled.Form component='form'>
I have used FormControl as a wrapper for each field and changed that to html form element

2022-02-27 20:08 UTC, Adys23 commented on libs/shared/src/types/form.ts
> +export enum FieldTypes {
Done

2022-02-27 20:08 UTC, Adys23 commented on libs/translations/src/feedback/en.json
> +  "save": "Save",
Moved to common

2022-02-27 20:10 UTC, Adys23 commented on libs/features/feedback/src/components/basic-presentation-info/index.tsx
> +      defaultValue: t(" "),
Adjusted

2022-02-27 20:10 UTC, Adys23 commented on libs/features/feedback/src/components/basic-presentation-info/index.tsx
> +      hasEditIcon: true
Done

2022-02-27 20:10 UTC, Adys23 commented on libs/features/feedback/src/components/basic-presentation-info/index.tsx
> +    {
Done

2022-02-27 20:12 UTC, Adys23 commented on libs/features/feedback/src/components/basic-presentation-info/index.tsx
> +      hasSubmitButton={false}
Ok

2022-02-27 20:12 UTC, Adys23 commented on libs/shared/src/components/form-field/index.tsx
> +
Done

2022-02-27 20:13 UTC, Adys23 commented on libs/shared/src/components/form-field/index.tsx
> +        error={errors[`${name}`]}
Moved to const

2022-02-27 20:14 UTC, Adys23 commented on libs/shared/src/components/form-field/index.tsx
> +        {...(errors[`${name}`] && { helperText: errors[`${name}`].message })}
Done

2022-02-27 20:14 UTC, Adys23 commented on libs/shared/src/components/form-field/index.tsx
> +        {...(!field.value && { defaultValue })}
Adjusted

2022-02-27 20:15 UTC, Adys23 commented on libs/shared/src/components/form-field/index.tsx
> +        {...(isMultiline && { rows: rows || 4 })}
Why should we avoid it?

2022-02-27 20:17 UTC, Adys23 commented on libs/shared/src/components/form-field/index.tsx
> +      {hasEditIcon && <Edit />}
I assumed you wanted to refer to `renderHelperText()` function, you mentioned earlier, so I moved that to the separate function.

2022-02-27 20:21 UTC, Adys23 commented on libs/shared/src/components/form/index.tsx
> +  const { ...methods } = useForm<FieldValues>({
No difference :)

2022-02-27 20:28 UTC, Adys23 commented on libs/shared/src/components/form/index.tsx
> +      <form className={className}>
This is done to pass styled-component css class through the FormProvider (which is not rendered) to the form component.
Thanks to that each form can have its own style. Box wrapper below form element will not bring any benefit, because the class would still be passed to FormProvider (not passed at all to the HTML elements). We could add Box wrapper above FormProvider, but I prefer to avoid creating HTML elements without specific reason.

![image](https://user-images.githubusercontent.com/37738097/155898666-b023cb6f-4320-434e-bfea-aa162fbe059f.png)

2022-02-27 20:28 UTC, Adys23 commented on libs/shared/src/components/form/index.tsx
> +        {formTitle && <Typography>{formTitle}</Typography>}
Done

2022-02-27 20:30 UTC, Adys23 commented on libs/shared/src/components/form/index.tsx
> +          <BaseButton type={ButtonType.Basic} onClick={methods.handleSubmit(onSubmit, onError)} variant='contained'>
Done. Why should we do it like that?

2022-02-27 20:32 UTC, Adys23 commented on libs/shared/tsconfig.json
> +    "noPropertyAccessFromIndexSignature": false,
It was previously set separately for each part, so I wanted to keep the information in the same manner. 

Changed that.

2022-02-27 20:36 UTC, Adys23 commented on libs/ui/src/stories/basic-presentation-info/basic-presentation-info.stories.tsx
> +export const BasicPresentationInfoStory: React.FC = () => <BasicPresentationInfo />;
Basic form looks pretty ugly, as it does not have any styles applied as default. Maybe you can give me a hint on how I should handle that? Separate Styled.Form for Story only? Apply some basic styles to the form (in this case we might mess up the specificity).

2022-02-28 12:40 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +          <BaseButton type={ButtonType.Basic} onClick={methods.handleSubmit(onSubmit, onError)} variant='contained'>
First of all to be consistent with project assumptions, second reason is related to the first one, since we are encapsulating inn handleSubmit we can easily find method responsible for submitting (take under consideration project where you have 1000 components and each is written in different manner or not consequently, reading the code is much more difficult) and if we'd like to extend this behaviour (maybe someone will have to then we have this separate method that contains logic)

2022-02-28 12:45 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +      <form className={className}>
Ok, I see, what I suggest is to create base style for the form like paddings, maxWidth etc... to have base form layout  same for all occurrences plus leave this className prop

2022-02-28 12:46 UTC, kacperChlon commented on libs/ui/src/stories/basic-presentation-info/basic-presentation-info.stories.tsx
> +export const BasicPresentationInfoStory: React.FC = () => <BasicPresentationInfo />;
I think your problem will be solved if you apply what I mentioned above - basic form layout

2022-02-28 12:48 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +      {hasEditIcon && <Edit />}
Gosh, I hate review on github :p 

<img width="292" alt="image" src="https://user-images.githubusercontent.com/97678763/155986002-6b2b965e-5194-4000-a859-3c4c84bb5793.png">

 it hides html elements in comments...

2022-02-28 12:50 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +        {...(isMultiline && { rows: rows || 4 })}
it makes code less readable

2022-02-28 13:43 UTC, Adys23 commented on libs/ui/src/stories/basic-presentation-info/basic-presentation-info.stories.tsx
> +export const BasicPresentationInfoStory: React.FC = () => <BasicPresentationInfo />;
Yup, looks fine now.

2022-02-28 13:43 UTC, Adys23 commented on libs/shared/src/components/form/index.tsx
> +      <form className={className}>
Done

2022-02-28 13:47 UTC, Adys23 commented on libs/features/feedback/src/components/title-and-description-form/styled.tsx
> +export const Form = styled(Box)<BoxProps>(({ theme }) => ({
Yes, they are. My VSC is throwing some strange errors at me from time to time...

2022-02-28 15:55 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-field.tsx
> +const DEFAULT_ROWS_NUMBER = 4;
please add empty space

2022-02-28 15:58 UTC, kacperChlon commented on libs/shared/src/components/form-field/form-field.tsx
> +import { FieldValues, useController, UseControllerProps, UseFormStateReturn } from "react-hook-form";
this file can be index.tsx

2022-02-28 15:58 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-field.tsx
> +interface Props {
RenderFieldProps

2022-02-28 16:01 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-field.tsx
> +  fieldType: FieldTypes;
type

2022-02-28 16:02 UTC, kacperChlon commented on libs/shared/src/types/field-types.ts
> +export enum FieldTypes {
FieldType

2022-02-28 18:06 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +  helperText: string | undefined;
helperText?: string

2022-02-28 18:14 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +export const renderHelperText = ({ helperText, error }: Props): JSX.Element | null =>
no need for return type, ts will figure it out

2022-02-28 18:14 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +interface Props {
RenderHelperTextProps

2022-02-28 18:15 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +interface Props {
or just make it simpler and do:

(helperText?: string, errors: FieldErrors) => ...

2022-02-28 18:16 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +  error: UseFormStateReturn<FieldValues>["errors"];
we are taking errors object hence it should be errors not error

2022-02-28 18:23 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +  helperText || error ? <FormHelperText error={!!error}>{(error && error.message) || helperText}</FormHelperText> : null;
and to make it more readable I'd suggest doing sth like this:

```
const renderHelperText = (error?: {}, text?: string) => {
    if(errors) {
        return <FormHelperText error>...</FormHelperText>
    }

    return helperText && <FormHelperText>{text}</FormHelperText>
}
```

2022-02-28 18:25 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +  title?: TFunction;
it should be type of string

2022-02-28 18:28 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +  onSubmit: SubmitHandler<FieldValues>;
if we can submit action we should also have cancelation action, hence there should be cancel button

2022-02-28 18:29 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-field.tsx
> +  label: string | undefined;
label?: string

2022-02-28 18:30 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-field.tsx
> +  variant: "standard" | "filled" | "outlined" | undefined;
variant?: "standard" | "filled" | "outlined"

2022-02-28 18:30 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-field.tsx
> +  value: any;
try unknown type instead of any

2022-02-28 18:33 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-field.tsx
> +export const renderField = ({ fieldType, fieldName, value, onChange, variant, error, label, rows }: Props): JSX.Element => {
variant = "outlined" then get rid of assertion variant || "outlined"

2022-02-28 18:43 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +        {fields.map(field => (
since we are creating dynamically our presentations there is a possibility to have form  without fields (user may remove every newly added field). In that case we should make fields optional and render a message to a user (custom - passed via props and default one - if not passed)

2022-02-28 18:44 UTC, kacperChlon commented on libs/ui/src/stories/form/form.stories.tsx
> +  console.log("submit");
error ;)

2022-02-28 19:29 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +  onChange: (...event: any[]) => void;
This type was taken from the react-hook-form controller.

![image](https://user-images.githubusercontent.com/37738097/156042166-6ffdf268-e697-48b8-b14c-fdb9eff3e3c5.png)

It is handled in form-field component and only passed to renderFormField function.

It has to remain required, otherwise we will not be able to control the field, but I was able to remove the array.

![image](https://user-images.githubusercontent.com/37738097/156046082-d54ca15d-c6a0-4f3b-8852-59b3b881af04.png)

2022-02-28 19:43 UTC, Adys23 commented on libs/shared/src/types/field-types.ts
> +export enum FieldTypes {
There are also other types of fields that can be handled in form, I was thinking they might be added in the future: 

FormFieldType.Select
FormFieldType.Switch
FormFieldType.Checkbox
FormFieldType.RadioButtons

2022-02-28 20:01 UTC, Adys23 commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +  helperText || error ? <FormHelperText error={!!error}>{(error && error.message) || helperText}</FormHelperText> : null;
Ad 1. It will show only the first helper text. After first condition is fulfilled it will show next one and so on...

Ad 2. This will not cover the case, when we do not want to have any helper text i.e. Description field in BasicPresentationInfo

2022-02-28 21:48 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +const DEFAULT_ROWS_NUMBER = 4;
Done

2022-02-28 21:48 UTC, Adys23 commented on libs/shared/src/components/form-field/form-field.tsx
> +import { FieldValues, useController, UseControllerProps, UseFormStateReturn } from "react-hook-form";
Done

2022-02-28 21:48 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +interface Props {
Done

2022-02-28 21:48 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +  fieldType: FieldTypes;
Done

2022-02-28 21:48 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +  fieldName: string;
Done

2022-02-28 21:48 UTC, Adys23 commented on libs/shared/src/components/form-field/styled.ts
> +    top: 10,
Done

2022-02-28 21:48 UTC, Adys23 commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +  helperText: string | undefined;
Done

2022-02-28 21:48 UTC, Adys23 commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +export const renderHelperText = ({ helperText, error }: Props): JSX.Element | null =>
Ok

2022-02-28 21:49 UTC, Adys23 commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +interface Props {
Done

2022-02-28 21:49 UTC, Adys23 commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +  error: UseFormStateReturn<FieldValues>["errors"];
Ok

2022-02-28 21:49 UTC, Adys23 commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +  helperText || error ? <FormHelperText error={!!error}>{(error && error.message) || helperText}</FormHelperText> : null;
Ad 2. Done

2022-02-28 21:49 UTC, Adys23 commented on libs/shared/src/components/form/index.tsx
> +  title?: TFunction;
Done

2022-02-28 21:49 UTC, Adys23 commented on libs/shared/src/components/form/index.tsx
> +  onSubmit: SubmitHandler<FieldValues>;
Done

2022-02-28 21:49 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +  label: string | undefined;
Done

2022-02-28 21:49 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +  rows: number | undefined;
Done

2022-02-28 21:49 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +  variant: "standard" | "filled" | "outlined" | undefined;
Done

2022-02-28 21:49 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +  value: any;
Ok

2022-02-28 21:50 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +export const renderField = ({ fieldType, fieldName, value, onChange, variant, error, label, rows }: Props): JSX.Element => {
Ok

2022-02-28 21:50 UTC, Adys23 commented on libs/shared/src/components/form/index.tsx
> +        {fields.map(field => (
Done

2022-02-28 21:50 UTC, Adys23 commented on libs/ui/src/stories/form/form.stories.tsx
> +  console.log("submit");
:)

2022-03-01 16:57 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-field.tsx
> +  onChange: (...event: any[]) => void;
What I meant is:

passed onChange should be used to handle some additional logic that parent needs but for handling field value there should be handleChange method created within form-field (or separate field) component, so we can have for instance:

const handleChange = (event) => {
onChange && onChange()

event...
}

the input will vary based on a field, hence we should create some generic base handleChange method and if some field will require more specific hanndleChange then it will do it witihn itself but onChange that is passed as a prop should be related to parent

2022-03-02 13:02 UTC, Adys23 commented on libs/shared/src/types/field-types.ts
> +export enum FieldTypes {
I messed up the naming. FormFieldType (now FormFieldProps) stores general values for each field, together with information about the type of field (FieldTypes) that we want to create.

2022-03-02 16:10 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +  helperText || error ? <FormHelperText error={!!error}>{(error && error.message) || helperText}</FormHelperText> : null;
Actually it depends on requirements, sometimes you need to show more than one, hence it's nnice to have such possibility in code. But sure, we can go with one error at a time and focus on next challenges :)

2022-03-02 16:16 UTC, kacperChlon commented on libs/shared/src/types/field-types.ts
> +export enum FieldTypes {
Please let me know WDYT on chat :) 
https://github.com/intive/patronage22-web-wroclaw/pull/31/files#r817856215

2022-03-02 16:17 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-field.tsx
> +  onChange: (...event: any[]) => void;
please let me know if you've got any concerns regarding this one on chat :)

2022-03-03 14:03 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +  onChange: (...event: any[]) => void;
No concerns :) I have added the handleChange function.

2022-03-03 14:04 UTC, Adys23 commented on libs/shared/src/types/field-types.ts
> +export enum FieldTypes {
Renamed it based on our conversation.

2022-03-03 14:05 UTC, Adys23 commented on libs/features/feedback/src/components/basic-presentation-info/index.tsx
> +  const fields: FormFieldType[] = [
Resolved, as per conversation.

2022-03-03 14:22 UTC, kacperChlon commented on libs/shared/src/components/action-card/styled.ts
>    backgroundColor: "#f7f7f7",
please add or use color from theme ;)

2022-03-03 14:31 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +  const fieldErrors: UseFormStateReturn<FieldValues>["errors"] = errors[`${name}`];
Do we need to wrap name in template literal?

2022-03-03 14:33 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +      {renderEditIcon(hideEditIcon)}
since this is very simple function, I think there is no need to make it, you can add here just `{hideEditIcon ?? <Edit />}`

2022-03-03 14:38 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-field.tsx
> +  const handleChange: ChangeEventHandler<HTMLTextAreaElement | HTMLInputElement> = event => {
As I wrote earlier, passed onChange is a side effect that we want to trigger from parent but to handle changeValue behaviour within form field it should have separate method encapsulated inn field file.

So, sample usage should look like this:
```

const handleChange = (event) => {
onChange && onChange()

formFieldValueChange(value)
}
```

2022-03-03 14:39 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +  if (errors) return <FormHelperText error={!!errors}>{errors.message}</FormHelperText>;
please use brackets for if statements

2022-03-03 14:40 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +    return placeholder ? (
```
return (<Typography id='placeholder' variant='h4'>
        {placeholder ?? {t("NoData")} }
</Typography>)
```

2022-03-03 14:41 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +    if (onCancel) onCancel();
onCancel && onCancel()

2022-03-03 14:42 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +
no need for empty space here :)

2022-03-03 18:40 UTC, Adys23 commented on libs/shared/src/components/form/index.tsx
> +    if (onCancel) onCancel();
it is forbidden in our project :) 

![image](https://user-images.githubusercontent.com/37738097/156630867-cfb07c0e-273f-438a-8e7d-3296659b2bfa.png)

2022-03-03 18:47 UTC, Adys23 commented on libs/shared/src/components/form/index.tsx
> +
I don't know. For me the hierarchy looked cleaner with it, especially as we have the spaces between rest of the siblings, but it is not something I would die for :)

2022-03-03 18:59 UTC, Adys23 commented on libs/shared/src/components/action-card/styled.ts
>    backgroundColor: "#f7f7f7",
Done

2022-03-03 19:00 UTC, Adys23 commented on libs/shared/src/components/form-field/index.tsx
> +  variant?: "standard" | "filled" | "outlined";
Done, hopefully FormTextFieldVariant is all right :)

2022-03-03 19:03 UTC, Adys23 commented on libs/shared/src/components/form-field/index.tsx
> +  const fieldErrors: UseFormStateReturn<FieldValues>["errors"] = errors[`${name}`];
Nope :)

2022-03-03 19:09 UTC, Adys23 commented on libs/shared/src/components/form-field/index.tsx
> +      {renderEditIcon(hideEditIcon)}
Ok

2022-03-03 19:09 UTC, Adys23 commented on libs/shared/src/components/form-field/render-helper-text.tsx
> +  if (errors) return <FormHelperText error={!!errors}>{errors.message}</FormHelperText>;
Ok

2022-03-03 19:10 UTC, Adys23 commented on libs/shared/src/components/form/index.tsx
> +    return placeholder ? (
Good point

2022-03-04 01:08 UTC, kacperChlon commented on libs/shared/src/components/form/index.tsx
> +    if (onCancel) onCancel();
Ok, strange I don't have such error but leave it and

<img width="362" alt="image" src="https://user-images.githubusercontent.com/97678763/156679648-d4e41a77-8ea7-456c-9123-e35175630218.png">

;)

2022-03-04 10:17 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +    field: { name: fieldName, value, onChange: controllerOnChange },
it's not controller that changes, it's onFieldChange

2022-03-04 10:25 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +    field: { name: fieldName, value, onChange: controllerOnChange },
`+` what's the reason in passing this name prop to useController if you need to take fieldName and pass it to renderField, wasn't it to be easier if you just pass name directly to renderField?

2022-03-04 10:28 UTC, kacperChlon commented on libs/features/feedback/src/components/basic-presentation-info/index.tsx
> +          fieldType: FormFieldType.Text,
please change this property to just 'type'

2022-03-04 10:29 UTC, kacperChlon commented on libs/shared/src/components/footer/style.ts
> +  backgroundColor: theme.palette.background.default,
let's change this file to styled.ts

2022-03-04 10:29 UTC, kacperChlon commented on libs/shared/src/components/form-field/index.tsx
> +    if (onChange) {
add space above

2022-03-04 10:32 UTC, kacperChlon commented on libs/shared/src/components/form-field/render-field.tsx
> +  disableUnderline?: boolean;
underline is a single word, hence please change to disableUnderline `+` underline functionality is not something you disable/enable, you rather show or hide it - please adjust the name accordingly to behaviour :)

2022-03-04 11:36 UTC, Adys23 commented on libs/features/feedback/src/components/basic-presentation-info/index.tsx
> +          fieldType: FormFieldType.Text,
Done

2022-03-04 11:36 UTC, Adys23 commented on libs/shared/src/components/footer/style.ts
> +  backgroundColor: theme.palette.background.default,
Done

2022-03-04 11:37 UTC, Adys23 commented on libs/shared/src/components/form-field/index.tsx
> +    if (onChange) {
Done

2022-03-04 11:37 UTC, Adys23 commented on libs/shared/src/components/form-field/render-field.tsx
> +  disableUnderline?: boolean;
I took the name from the MUI Input prop I wanted to use: https://mui.com/api/input/
but I finally decided I will not use it at all :)

2022-03-04 14:58 UTC, kacperChlon approved these changes

2022-03-04 20:11 UTC, merged